---
- name: Install node and npm
  hosts: webserver
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install nodejs and npm
      apt: 
        pkg:
        - nodejs
        - npm

- name: Create new Linux user for node app
  hosts: webserver
  vars_files:
    - project-vars
  tasks:
    - name: Create linux user
      user:
        name: abdul
        comment: abdul admin
        group: admin
      register: user_creation_result
    - debug: msg={{user_creation_result}}

#copy on prem tar file to server 
- name: Deploy nodejs app
  hosts: webserver
  become: True
  become_user: abdul
  vars_files:
    - project-vars  
  tasks: 
    # - name: Copy nodejs folder to a server
    #   copy:
    #     src: "{{location}}"
    #     dest: "{{destination}}/app-{{version}}.tgz"

    - name: Unpack the nodejs tar file
      unarchive:
        src: "{{location}}/nodejs-app-{{version}}.tgz"
        dest: "{{destination}}"
      register: user_creation_result
    - debug: msg={{user_creation_result}}
    - name: Remove file (delete file)
      file:
        path: "{{destination}}/package/nodejs-app-1.0.0.tgz"
        state: absent
    - name: Install dependencies
      community.general.npm:
        path: "{{destination}}/package"
    - name: Start the application
      command: 
        chdir: "{{destination}}/package/app" 
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}


 
        



